# Generated by Django 4.2.11 on 2024-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_coordinador_coordinadorlengua_coordinadortecnologia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='actividades_externas',
        ),
        migrations.RemoveField(
            model_name='director',
            name='actividades_meduca',
        ),
        migrations.RemoveField(
            model_name='director',
            name='actividades_propias_centro',
        ),
        migrations.RemoveField(
            model_name='director',
            name='after_school_participacion',
        ),
        migrations.RemoveField(
            model_name='director',
            name='asignaturas_ingles',
        ),
        migrations.RemoveField(
            model_name='director',
            name='asignaturas_otros_ingles',
        ),
        migrations.RemoveField(
            model_name='director',
            name='detalle_actividades_anuales',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes_capacitados_exterior',
        ),
        migrations.RemoveField(
            model_name='director',
            name='estudiantes_actividades_externas',
        ),
        migrations.RemoveField(
            model_name='director',
            name='estudiantes_por_nivel_ppb',
        ),
        migrations.RemoveField(
            model_name='director',
            name='geolocalizacion',
        ),
        migrations.RemoveField(
            model_name='director',
            name='plan_estudio_codigos',
        ),
        migrations.RemoveField(
            model_name='director',
            name='plan_estudio_detalle',
        ),
        migrations.RemoveField(
            model_name='director',
            name='planes_clase_contraste',
        ),
        migrations.RemoveField(
            model_name='director',
            name='recursos_multimedia',
        ),
        migrations.AddField(
            model_name='director',
            name='after_school_participacion_1',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='after_school_participacion_2',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='after_school_participacion_3',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='after_school_participacion_4',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='after_school_recursos',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='asignaturas_ingles_dictadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='asignaturas_ingles_plan_estudios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='codigos_plan_estudio',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_asignatura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitacion_exterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_nivel_ppb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_salon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='femenino1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='femenino2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='femenino3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='femenino4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='grado1',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='grado2',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='grado3',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='grado4',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='masculino1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='masculino2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='masculino3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='masculino4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='planes_clase',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='planes_estudio',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='total_docentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='director',
            name='after_school_descripcion',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='director',
            name='apellido',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='cedula',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='director',
            name='codigo_siace',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='director',
            name='correo_institucional',
            field=models.EmailField(default='N/A@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='director',
            name='correo_personal1',
            field=models.EmailField(default='N/A@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='director',
            name='correo_personal2',
            field=models.EmailField(default='N/A@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='director',
            name='direccion',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='director',
            name='nivel_escolar',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre_centro_educativo',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='director',
            name='provincia',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='region_educativa',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='telefono_oficina',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='director',
            name='telefono_personal',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
