# Generated by Django 4.2.11 on 2024-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_director_actividades_externas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='actividades_externas_centro',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='actividades_meduca_centro',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='actividades_propio_centro',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='cantidad_estudiantes_actividades_externas_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='cantidad_estudiantes_actividades_externas_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='cantidad_estudiantes_actividades_externas_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='cantidad_estudiantes_actividades_externas_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='detalle_actividades_anual',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='director',
            name='after_school_existencia',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='director',
            name='asignaturas_ingles_dictadas',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='director',
            name='asignaturas_ingles_plan_estudios',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='director',
            name='participa_ppb',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
